const db=window.supabase.createClient("https://bimttawmwzuzlbzgpbqo.supabase.co","sb_publishable_TTQQPHcHGI_a_47m3k_ujg_AN0MpqDA");
let cart=JSON.parse(localStorage.getItem("accestech_cart")||"[]");
const count=document.getElementById("cartCount"),cm=document.getElementById("cartModal"),items=document.getElementById("cartItems"),ct=document.getElementById("cartTotal");
function render(){count.textContent=cart.reduce((s,x)=>s+x.q,0);let t=0;items.innerHTML=cart.length?cart.map((x,i)=>{t+=x.p*x.q;return `<div class="cart-item"><span>${x.n}<br>${x.p} TND × ${x.q}</span><span><button onclick="chg(${i},-1)">−</button> <button onclick="chg(${i},1)">+</button></span></div>`}).join(""):"<p>Votre panier est vide.</p>";ct.textContent=t+" TND";localStorage.setItem("accestech_cart",JSON.stringify(cart))}
window.chg=(i,d)=>{cart[i].q+=d;if(cart[i].q<1)cart.splice(i,1);render()};
function bindProducts(){document.querySelectorAll(".add-btn").forEach(b=>b.onclick=()=>addToCart(b.dataset.product,Number(b.dataset.price)));document.querySelectorAll(".order-btn").forEach(b=>b.onclick=()=>openOrder(b.dataset.product,Number(b.dataset.price),1))}
function addToCart(n,p){if(Number(p)<=0){alert("Prix à définir pour ce produit. Modifiez-le depuis l'Admin.");return}const existing=cart.find(x=>x.n===n&&x.p===p);if(existing)existing.q++;else cart.push({n,p,q:1});render()}
document.getElementById("cartLink").onclick=e=>{e.preventDefault();render();cm.hidden=false};document.getElementById("closeCart").onclick=()=>cm.hidden=true;
const orderModal=document.getElementById("orderModal"),product=document.getElementById("product"),price=document.getElementById("price"),quantity=document.getElementById("quantity"),selectedProduct=document.getElementById("selectedProduct"),orderTotal=document.getElementById("orderTotal"),orderMessage=document.getElementById("orderMessage");
function openOrder(n,p,q){if(Number(p)<=0){alert("Prix à définir pour ce produit. Modifiez-le depuis l'Admin.");return}product.value=n;price.value=p;quantity.value=q;selectedProduct.textContent=n+" — "+p+" TND";orderTotal.textContent=(p*q)+" TND";orderMessage.textContent="";orderModal.hidden=false}
document.getElementById("closeOrder").onclick=()=>orderModal.hidden=true;quantity.oninput=()=>orderTotal.textContent=(Number(price.value)*Math.max(1,Number(quantity.value)))+" TND";
document.getElementById("cartCheckout").onclick=()=>{if(!cart.length)return;let n=cart.map(x=>x.n+" × "+x.q).join(", "),t=cart.reduce((s,x)=>s+x.p*x.q,0);cm.hidden=true;openOrder(n,t,1)};
document.getElementById("orderForm").onsubmit=async e=>{e.preventDefault();orderMessage.textContent="Enregistrement…";let q=Math.max(1,Number(quantity.value)),p=Number(price.value),g=document.getElementById("governorate").value.trim(),a=document.getElementById("address").value.trim(),n=document.getElementById("notes").value.trim();let r=await db.from("orders").insert([{customer_name:document.getElementById("customer_name").value.trim(),phone:document.getElementById("phone").value.trim(),address:a+" — "+g+(n?" — Note: "+n:""),products:[{name:product.value,quantity:q,unit_price:p}],total:Number((p*q).toFixed(2)),status:"pending"}]);if(r.error)orderMessage.textContent="Erreur lors de l'envoi. Vérifiez la connexion puis réessayez.";else{orderMessage.textContent="Commande confirmée avec succès ✓";cart=[];render()}};
async function loadProducts(){const grid=document.querySelector('.products');if(!grid)return;const {data,error}=await db.from('products').select('*').eq('active',true).order('sort_order',{ascending:true});if(error||!data||!data.length){bindProducts();return}grid.innerHTML=data.map(p=>{const cls=(p.category||'accessoires').toLowerCase();const visual=p.image_url?`<img src="${escapeAttr(p.image_url)}" alt="${escapeAttr(p.name)}">`:escapeHtml(p.badge||p.category||'TECH');return `<article class="card" data-category="${escapeAttr(p.category)}"><div class="visual ${cls}">${visual}</div><p class="tag">${escapeHtml(p.category)}</p><h3>${escapeHtml(p.name)}</h3><p class="product-desc">${escapeHtml(p.description||'')}</p><div class="bottom"><strong class="price">${Number(p.price)>0?Number(p.price).toFixed(2)+' TND':'Prix à définir'}</strong><div class="product-actions"><button class="add-btn" type="button" data-product="${escapeAttr(p.name)}" data-price="${Number(p.price)}">Ajouter au panier</button><button class="order-btn" type="button" data-product="${escapeAttr(p.name)}" data-price="${Number(p.price)}">Commander</button></div></div></article>`}).join('');bindProducts()}
function escapeHtml(v){return String(v??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]))}function escapeAttr(v){return escapeHtml(v).replace(/`/g,'&#96;')}
render();loadProducts();
